import uuid
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

class UserType(Enum):
    """
    UserType - Defines the type of the User

    Parameters:
        type (str): The user type. Possible values are "user" and "admin".
    
    Returns:
        type (str): gives type of the User as output

    Example:
        user = UserType("user")
        print(user)  # output: `UserType.user`
    """

    user = "user"
    admin = "admin"


user = UserType("user") 
admin = UserType("admin")


class User:
    """
    Defines the User class.

    Args:
        username (str): The username of the user.
        password (str): The password of the user.
        user_type (UserType): The type of the user (user or admin).
        session_id (Optional[str]): The session ID of the user (default is None).

    Methods:
        login(password): Checks if the provided password matches the user's password.
        logout(): Logs out the user by setting the session ID to None.
        is_authenticated(): Returns True if the user is authenticated (session ID is not None), False otherwise.
        is_admin(): Returns True if the user is an admin, False otherwise.
    """
    def __init__(self, username: str, password: str, user_type: UserType):
        self.username = username
        self.password = password
        self.user_type = user_type
        self.session_id: Optional[str] = None

    def login(self, password: str) -> bool:
        """
        Checks if the provided password matches the user's password.

        Args:
            password (str): The password to check.

        Returns:
            bool: True if the password matches, False otherwise.
            """

        if self.password == password:
            self.session_id = str(uuid.uuid4())
            return True
        return False

    def logout(self):
        self.session_id = None

    def is_authenticated(self) -> bool:
        return self.session_id is not None

    def is_admin(self) -> bool:
        return self.user_type == UserType.admin

class UserManager:
    """
    Manages the user authentication.
    
    Attributes:
        current_user (User): The currently authenticated user (optional parameter). 
        users: Dict[str, User]: A dictionary of users. Autogenerated from the pseudo database.

    Methods:
        login(username, password): Logs in a user with the provided username and password.
        logout(): Logs out the current user.
        register(username, password, user_type): Registers a new user with the provided username, password, and user_type.
        
        
    """
    def __init__(self):
        """
        Generates a dictionary of users on initialization and if the User is passed as an argument (optional), it will be added as a current_user, otherwise is None.
        """
        self.users: Dict[str, User] = {
            "user": User("user", "pass123", UserType.REGULAR),
            "admin": User("admin", "admin123", UserType.ADMIN)
        }
        self.current_user: Optional[User] = None

    def login(self, username: str, password: str) -> bool:
        """
        Logs in a user with the provided username and password.

        Args:
            username (str): The username of the user to log in.
            password (str): The password of the user to log in.

        Returns:
            bool: True if the login is successful, False otherwise.
        """
        if username in self.users:
            user = self.users[username]
            if user.login(password):
                self.current_user = user
                return True
        return False

    def logout(self):
        """
        Logs out the curent user.
        """
        if self.current_user:
            self.current_user.logout()
            self.current_user = None

    def register(self, username: str, password: str, user_type: UserType = UserType.user) -> bool:
        """
        Registers a new user with provided username, password, and user type.

        Args:
            username (str): The username of the new user.
            password (str): The password of the new user.
            user_type (UserType): The type of the new user (default is UserType.user).
        Returns:
            bool: True if the user is successfully registered, False otherwise
        """
        # if user is already in the database, return False
        if username in self.users:
            return False
        self.users[username] = User(username, password, user_type)
        return True
